import matplotlib.pyplot as plt

def metrics_OCR(history, save_path_accuracy, save_path_loss, save_path_character_acc, save_path_word_acc):
    
    epochs=range(1, len(history.history['accuracy'])+1)
    #Plot for accuracy
    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    plt.plot(epochs, history.history['accuracy'], label='Accuracy on training set', color='blue')
    plt.plot(epochs, history.history['val_accuracy'], label='Accuracy on validation set', color='green')
    plt.title('Accuracy')
    plt.xlabel('epoch')
    plt.ylabel('Accuracy')
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path_accuracy)
    plt.show()
    plt.close()
    #Plot for loss
    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    plt.plot(epochs, history.history['loss'], label='Loss on training set', color='blue')
    plt.plot(epochs, history.history['val_loss'], label='Loss on validation set', color='green')
    plt.title('Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path_loss)
    plt.show()
    plt.close()
    #Plt for character accuracy
    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    plt.plot(epochs, history.history['character_accuracy'], label='Character accuracy on training set', color='blue')
    plt.plot(epochs, history.history['val_character_accuracy'], label='Character accuracy on validation set', color='green')
    plt.title('Character Accuracy')
    plt.xlabel('epoch')
    plt.ylabel('Char accuracy')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(save_path_character_acc)
    plt.show()
    plt.close()
    #Plot for word accuracy
    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    plt.plot(epochs, history.history['word_accuracy'], label='Word accuracy on training set', color='blue')
    plt.plot(epochs, history.history['val_word_accuracy'], label='Word accuracy on validation set', color='green')
    plt.title('Word accuracy')
    plt.xlabel('epochs')
    plt.ylabel('Word accuracy')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(save_path_word_acc)
    plt.show()
    plt.close()

